import Head from "next/head"
import styles from "../styles/Home.module.css"
import Header from "../components/Header"
import MintNFT from "../components/MintNFT"
import { useMoralis } from "react-moralis"
// import background from "../public/preview.png"

const supportedChains = ["31337", "11155111", "5"]

export default function Home() {
    const { isWeb3Enabled, chainId } = useMoralis()

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <br />
            <br />

            <br></br>

            <div className="flex flex-row justify-between">
                <img
                    src="/preview.gif"
                    alt="My Image"
                    className="rounded-full h-40 ml-40"
                />
                <MintNFT />
                <img
                    src="/preview.gif"
                    alt="My Image"
                    className="rounded-full h-40 mr-40"
                />
            </div>
        </div>
    )
}
